os: osx
osx_image: xcode9.2

language: node_js
node_js:
  - "8"
  - "10"

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

git:
  depth: 5

before_install:
  - |
  - cd packages/graphql-playground-react
  - yarn link

install:
  - |
  - cd ..
  - cd packages/graphql-playground-electron
  - yarn link graphql-playground-react
  - yarn install
  - yarn release

notifications:
  email: false

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file_glob: true
  prerelease: true
  file:
    - packages/graphql-playground-electron/build-electron/GraphQL Playground Setup 1.8.0.exe
    - build-electron/GraphQL Playground Setup 1.8.0.exe